import "@/sass/globals.scss";
import styles from "./_index.module.scss"
import type { Metadata } from "next";
import Header from "../components/organisms/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function LabLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>
    <html lang="ja" className={`${styles.html}`}>
      <body className={`${styles.body}`}>
        <Header />
        {children}
      </body>
    </html>
  </>
}
