import "@/sass/globals.scss";
import styles from "./_index.module.scss"
import type { Metadata } from "next";
import Header from "../components/organisms/Header";
import Loading from "../components/organisms/Loading";
import StoreProvider from "@/lib/store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function LabLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>
    <html lang="ja" className={`${styles.html}`}>
      <StoreProvider>
        <body className={`${styles.body}`}>
          <div className={`${styles.header}`}>
            <Header />
          </div>
          <div className={`${styles.loading}`}>
            <Loading />
          </div>
          {children}
        </body>
      </StoreProvider>
    </html>
  </>
}
